language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
  - tar xf arduino-1.8.9-linux64.tar.xz
  - sudo mv arduino-1.8.9 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/SparkFun_MCP9600_Arduino_Library
  - arduino --install-library "SparkFun MCP9600 Arduino Library"
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example1_BasicReadings/Example1_BasicReadings.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example2_SetThermocoupleType/Example2_SetThermocoupleType.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example3_SetFilterCoefficient/Example3_SetFilterCoefficient.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example4_SetResolution/Example4_SetResolution.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example5_BurstMode/Example5_BurstMode.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example6_ConfigureTemperatureAlert/Example6_ConfigureTemperatureAlert.ino 
notifications:
  email:
    on_success: change
    on_failure: change